version: '3.8'

services:
  kmouse:
    build: .
    volumes:
      - .:/app:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    #command: bash -c "cmake . && make && ./kmouse"
    command: bash -c "cmake . && make && ./onlydebug.sh"
